---
- name: Ensure MAS is installed.
  homebrew: name=mas state=present

- name: Sign in to MAS when email and password are provided.
  shell: 'mas signin "{{ mas_email }}" "{{ mas_password }}"'
  register: mas_signin_result
  when: mas_email != '' and mas_password != ''

- name: List installed MAS apps.
  command: mas list
  register: mas_list
  check_mode: no
  changed_when: false

- name: Ensure configured MAS apps are installed.
  command: mas install "{{ item }}"
  with_items: "{{ mas_installed_app_ids }}"
  when: "'{{ item }}' not in mas_list.stdout"

- name: Upgrade all apps (if configured).
  command: mas upgrade
  when: mas_upgrade_all_apps
